
spring:
  application:
    name: zuul-gateway-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  healthcheck:
    enabled: true

server:
  port: 8484
zuul:
  routes:
    foos:
      path: /api/**
      url: http://host.docker.internal:8089/

